apiVersion: v1
appVersion: 1.15.2
description: Telegraf is an agent written in Go for collecting, processing, aggregating,
  and writing metrics.
home: https://www.influxdata.com/time-series-platform/telegraf/
keywords:
- telegraf
- collector
- timeseries
- influxdata
- influxdb
- agent
maintainers:
- email: rawkode@influxdata.com
  name: rawkode
- email: giacomo@influxdata.com
  name: gitirabassi
name: telegraf
version: 1.0.0
